[project]
authors = ["acorrao <95718914+AdamCorrao@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "pub-Corrao_2025_09"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.2,<3"
xarray = ">=2025.8.0,<2026"
pathlib = ">=1.0.1,<2"
matplotlib = ">=3.10.6,<4"
tqdm = ">=4.67.1,<5"
scikit-learn = ">=1.7.1,<2"
scipy = ">=1.16.1,<2"
joblib = ">=1.5.2,<2"
opencv = ">=4.12.0,<5"
ipython = ">=9.5.0,<10"
ipywidgets = ">=8.1.7,<9"
ipykernel = ">=6.30.1,<7"
dask = ">=2025.7.0,<2026"
netcdf4 = ">=1.7.2,<2"
bottleneck = ">=1.5.0,<2"
ipympl = ">=0.9.7,<0.10"
nbstripout = ">=0.8.1,<0.9"
